### ISSUE TITLE
Implement automated testing

### ISSUE THREAD

**Issue by alallema** [vivesvoies/court-message#104]
## Description:
The implementation of automated tests after the push via a GitHub Actions will be an additional security to verify that the tests pass correctly.

## Todo:
- [x] Create a worflow file `.yaml`
- [x] Setup the action in github
- [ ] Check that [Scalingo](https://dashboard.scalingo.com/apps/osc-fr1/court-message-alpha/deploy/config) takes this into account in the deployment parameters
