### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by alallema** [vivesvoies/court-message#105]
## Description:
It would be good to develop the documentation. A non-exhaustive list is already available on the readme.
Depending on the future of the project a contributing file could be added this could also act as a penses betes for people working on the project.

## Todo:

- [ ] How launch the project on your local environment.
- [ ] How launch the project for production ?
- [ ] Short description of pipeline tools used
