### ISSUE TITLE
🍔 Template

### ISSUE THREAD

**Issue by alallema** [vivesvoies/court-message#99]
[See spec](https://www.figma.com/file/imcD3RPEbSwrBzqcU6i2w7/Court-Message?type=design&node-id=911-2367&mode=design&t=qBhF1P5TdZINxKBU-0)
- [x] Create Template Class
- [x] Create ready-to-use templates
- [x] Should be able to create new template
- [x] Should be able to edit already existing template
- [x] Should be able to destroy template

Check how to create new model and template
